---

# opening worker ports
- name: firewall configuration1 for master
  firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  become: true
  with_items:
   - 10250/tcp
   - 30000-32767/tcp

- name: Creating a file with content
  copy:
    dest: "/home/ansible/token2.sh"
    content: "{{ hostvars['DUMMY_HOST']['PLAY1VAR_NEW'] }}"
  become: yes

- name: Ansible replace string 
  replace:
    path:  "/home/ansible/token2.sh"
    regexp: "[\]"
  become: yes

- name: Echo the output token file vaule
  shell: sed 's/\\n//g' /home/ansible/token2.sh 
  register: kubeadmExit

- debug: msg=" {{ kubeadmExit.stdout }}"

- name: Run a script with arguments (free form)
  command: "sh /home/ansible/token2.sh"
  become: yes

# Reload config.
- firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
  become: yes

# Reload config.
- name: reload
  command: /home/ansible/token2.sh
  become: yes

- lineinfile:
    path: /etc/apt/sources.list
    regexp: '\-updates main'
    state: absent
    backup: yes