---

# opening worker ports
- name: firewall configuration1 for master
  firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  become: true
  with_items:
   - 10250/tcp
   - 30000-32767/tcp

- name: Creating a file with content
  copy:
    dest: "/home/ansible/token2.sh"
    content: "{{ hostvars['DUMMY_HOST']['PLAY1VAR_NEW'] }}"
  become: yes

- name: images config
  command: ""{{kubeadmExit2.stdout}}" --ignore-preflight-errors=all"
  become: yes
  register: kubeadmExit

- name: Run a script with arguments (using 'cmd' parameter)
  script:
    cmd: /home/ansible/token2.sh
  remote_src: yes

- debug: msg="{{kubeadmExit2.stdout}}"

# Reload config.
- firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
  become: yes

# Reload config.
- name: reload
  command: /home/ansible/token2.sh
  become: yes

- lineinfile:
    path: /etc/apt/sources.list
    regexp: '\-updates main'
    state: absent
    backup: yes