---

# opening worker ports
- name: firewall configuration1 for workers
  firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  become: true
  with_items:
   - 10250/tcp
   - 30000-32767/tcp
   - 8285/udp
   - 8472/udp

- name: Creating a file with content
  copy:
    dest: "/home/ansible/token2.sh"
    content: "{{ hostvars['DUMMY_HOST']['PLAY1VAR_NEW'] }}"
  become: yes

- name: Echo the output token file vaule
  shell: sed 's/\\//g' /home/ansible/token2.sh 
  register: kubeadmExit

- debug: msg=" {{ kubeadmExit.stdout }}"

#- name: kubeadm reset
#  command: "kubeadm reset -f"
#  become: yes

- name: Kubeadm join
  command: "{{kubeadmExit.stdout}}"
  become: yes

# Reload config.
- firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
  become: yes