---

# opening worker ports
- name: firewall configuration1 for master
  firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  become: true
  with_items:
   - 10250/tcp
   - 30000-32767/tcp


- name: Echo the output kubeadmExit variable vaule last line
  shell: cat /home/ansible/kubeadmFile |tail -f | grep 'discovery-token-ca-cert-hash'
  register: kubeadmExit2

- debug: msg="{{kubeadmExit2.stdout}}"

# Reload config.
- name: reload
  command: "kubeadm join 10.0.1.11:6443 --token gmk4le.8gsfpknu99k78qut {{kubeadmExit2.stdout}}"
  become: yes

- lineinfile:
    path: /etc/apt/sources.list
    regexp: '\-updates main'
    state: absent
    backup: yes