---

# opening worker ports
- name: firewall configuration1 for master
  firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  become: true
  with_items:
   - 10250/tcp
   - 30000-32767/tcp

# Starting docker
- name: restarting up docker config
  systemd:
    name: docker
    state: restarted
    force: yes
    enabled: yes
    masked: no
  become: yes

# Rtarting kubernetes
- name: Starting kubelet
  systemd:
    name: kubelet 
    state: started
    enabled: yes
    masked: no
    daemon_reexec: yes
  become: yes

- name: Starting kubelet
  systemd:
    name: kubectl
    state: started
    enabled: yes
    masked: no
    daemon_reexec: yes
  become: yes

- name: Creating a file with content
  copy:
    dest: "/home/ansible/token2.sh"
    content: "{{ hostvars['DUMMY_HOST']['PLAY1VAR_NEW'] }}"
  become: yes

- name: Echo the output token file vaule
  shell: sed 's/\\//g' /home/ansible/token2.sh 
  register: kubeadmExit

- debug: msg=" {{ kubeadmExit.stdout }}"

- name: kubeadm reset
  command: "kubeadm reset -f"
  become: yes

- name: Kubeadm join
  command: "{{kubeadmExit.stdout}} --ignore-preflight-errors=all"
  become: yes

# Reload config.
- firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
  become: yes

# Get nodes
- name: get nodes
  command: kubectl get nodes
  become: yes

- lineinfile:
    path: /etc/apt/sources.list
    regexp: '\-updates main'
    state: absent
    backup: yes