---

# Install and enable nfs server 
- name: install nfs-utils
  dnf:
    name: 
       - nfs-utils 
       - net-tools
    state: latest
  become: yes

- name: start nfs-server
  service:
    name: "nfs-server"
    state: "started"
    enabled: true
  become: true

   
   

# copy export file content into /etc/exports
- name: copy export fileto /etc/exports
  copy:
    src: "/files/{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
      - "export"

