---

# opening firewall ports
- name: Opening ports
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
   - nfs
   - rpc-bind
   - mountd
  
 # Reload config.
- firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
    zone: dmz