---

# Installing tigera operator.
- name: install Tigera
  command: "kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml"
  become: yes

# Install Calico: definition file
- name: Download foo.conf
  get_url:
    url: https://docs.projectcalico.org/manifests/custom-resources.yaml
    dest: /tmp/
    force: yes
  become: yes

- name: Replace cidr entry with POD IP
  lineinfile:
    path: /tmp/custom-resources.yaml
    regexp: '^(.*)cidr:(.*)'
    line: '      cidr: 10.1.1.0/16'
    owner: root
    group: root
    mode: '0644'
  become: yes

# Installing Calico.
- name: Installing Calico
  command: "kubectl apply -f /tmp/custom-resources.yaml"
  become: yes

- name: Installing Calico
  command: "kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml "
  become: yes