---

# Installing ingress controller.
- name: install ingress controller
  command: "kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml"
  become: yes

# Generating hash password
# generate a random value for use it as salt and then save in to a variable
# with delegate_to the task is executed locally
- name: enerate a random value for use it as salt for generate the password
  command: /usr/bin/openssl rand -base64 32
  register: random_pass
  

- name: make the hash (sha512)
  command: "/usr/bin/openssl passwd -6 -salt {{ random_pass.stdout }} {{ password }}"
  register: password_sha512

- name: Add user
  user:
    name: kubeadmin
    password:  "{{ password_sha512.stdout }}"
  become: yes

# Allow kubeadmin user to acces into the cluster

- name: create a directory if it does not exist
  file:
    path: "/home/kubeadmin/.kube"
    state: directory
    mode: '0755'
  become: yes

- name: Authorize user cluster access
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Change kubeconfig file permission
  file:
    path: /root/.kube/config 
    owner: root
    group: root
  become: yes 


# No password needed for this usser
- name: Kubernetes no password needed
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: kubeadmin
    group: root
    mode: '0644'
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
      - "kubeadmin"