---

# Installing ingress controller.
- name: install ingress controller
   command: "kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml"
   become: yes

# Allow kubeadmin user to acces into the cluster
- name: create a directory if it does not exist
  file:
    path: "/home/kubeadmin/.kube"
    state: directory
    mode: '0755'
  become: yes

- name: Authorize user cluster access
  command: "cp -i /etc/kubernetes/admin.conf /root/.kube/config"
  become: yes 

- name: Authorize user cluster access
  command: "chown $(id -u):$(id -g) /home/kubeadmin/.kube/config"
  become: yes 

# No password needed for this usser
- name: Kubernetes no password needed
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: kubeadmi
    group: master
    mode: '0644'
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
      - "kubeadmin"