---

- name: enable services
  systemd:
   name: "{{ item }}"
   state: started
   enabled: yes
   masked: no
  become: yes
  with_items:
    - "chronyd"
    - "firewalld"

- name: start Timedatectl
  command: /usr/bin/timedatectl set-ntp true
  become: yes