---

- name: enable services
  systemd:
   name: "{{ chrony }}"
   state: started
   enabled: yes
   masked: no
 become: yes
 with_items:
  - "{{ chrony} }"

- name: start Timedatectl
  command: timedatectl set-ntp true
  
