---

# copy hopsts file content into /etc/hosts with ip addresses of all vm
- name: copy hosts fileto /etc/hosts
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
      - "hosts"
