---

# Kubernetes repository config
- name: Kubernetes trafic management
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
      - "kubernetes.repo"

# installing kubernetes
- name: installing kubernetes
  dnf:
    name: 
     - kubelet 
     - kubeadm 
     - kubectl
    state: present
  become: yes

# Starting kubelet
- name: Starting kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  become: yes

# Reload config.
- firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
  become: yes

