---

- name: master config
  hosts: 
    - 10.0.1.10
  gather_facts: true
  vars_prompt:
    # pregunta por teclado una contraseña y la almacena en la variable password
    # con private controlamos si queremos que la contraseña introducida se vea en la terminal al escribirla,
    # con esta configuración no se verá
    - name: password
      prompt: Introduce una contraseña para generar el hash
      private: yes
  roles:
    - master