---

# Install and enable nfs server 
- name: install nfs-utils
  dnf:
    name: 
       - nfs-utils 
       - net-tools
    state: latest
  become: yes

- name: start nfs-server
  service:
    name: "nfs-server"
    state: "started"
    enabled: yes
    daemon_reload: yes
  become: yes 

# copy export file content into /etc/exports
- name: copy export file to /etc/exports
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
      - "exports"

# opening firewall ports
- name: Opening ports
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
   - nfs
   - rpc-bind
   - mountd
  become: yes

 # Reload config.
- firewalld:
    masquerade: yes
    state: enabled
    permanent: true
  become: yes